Joyce send key
Bora-CS/batch9-cucumber-framework pull request #2
Opened 2023-02-08 14:36 UTC by joycechen612

please help review . thanks

2023-02-08 14:38 UTC, Wei1150 approved these changes, later dismissed
LGTM

2023-02-08 14:47 UTC, WenjiZ approved these changes, later dismissed

2023-02-08 14:51 UTC, ShaolingStouder commented
LGTM!

2023-02-08 14:53 UTC, ShaolingStouder approved these changes, later dismissed

2023-02-08 15:00 UTC, minyizeng approved these changes, later dismissed
Good job

2023-02-09 22:38 UTC, boratech-macmini requested changes
Formatting is off

2023-02-09 22:38 UTC, boratech-macmini commented on src/test/java/utilities/Util.java
> +		WebElement ele = driver.findElement(By.xpath(xpathLocator));
Instead of passing in xpathLocator, pass in a `By` object would make it more reusable

2023-02-09 23:51 UTC, minyizeng submitted a review, later dismissed

2023-02-12 05:46 UTC, closed without merging