Wenji add a method
Bora-CS/batch9-cucumber-framework pull request #3
Opened 2023-02-08 14:43 UTC by WenjiZ

2023-02-08 14:45 UTC, joycechen612 approved these changes
Great!

2023-02-08 14:46 UTC, Wei1150 approved these changes
LGTM

2023-02-08 14:56 UTC, ShaolingStouder approved these changes
LGTM!

2023-02-09 22:45 UTC, boratech-macmini requested changes

2023-02-09 22:45 UTC, boratech-macmini commented on src/test/java/utilities/Util.java
> +		Select dropDown = new Select(driver.findElement(By.xpath(dorpDownXpath)));
1, Instead of xpath as a parameter, pass in a `By` object, makes it more reusable
2, make sure you format the file

2023-02-09 22:46 UTC, boratech-macmini commented
After you address your review comments, make sure to resolve conflicts

2023-02-10 14:14 UTC, closed without merging