add isDisplayed method
Bora-CS/batch9-cucumber-framework pull request #7
Opened 2023-02-08 17:34 UTC by NiluparErkin

2023-02-08 17:41 UTC, WenjiZ approved these changes, later dismissed
LGTM!

2023-02-08 17:43 UTC, Jack-Vu submitted a review, later dismissed
LGTM!

2023-02-08 18:46 UTC, Wei1150 approved these changes, later dismissed
LGTM!

2023-02-09 22:52 UTC, boratech-macmini requested changes

2023-02-09 22:52 UTC, boratech-macmini commented on src/test/java/utilities/Util.java
> +	public static boolean isElementDisplayed(WebDriver driver, String xPathOfElement) {
It would be a better idea to use By object instead of xpath, would be more reusable

2023-02-09 23:21 UTC, Wei1150 approved these changes

2023-02-09 23:21 UTC, boratech-macmini approved these changes

2023-02-09 23:22 UTC, merged